language: java
jdk:
  - oraclejdk8
before_install:
  - "./gradlew --version"
  - mysql -e 'create database daleq_test;'
install: "./gradlew --stacktrace --quiet --no-color assemble"
script: "./travis_build.sh"
after_script:
  - "./gradlew --stacktrace --quiet --continue --no-color issues"
notifications:
  email:
    recipients:
      - l.girndt@googlemail.com
